import type { Project, ProjectFilterOption } from "../types";

// Fixed: filter labels aligned with test expectations
export const PROJECT_FILTERS: ProjectFilterOption[] = [
  { value: "all", label: "All Projects" },
  { value: "rn", label: "React Native" },
  { value: "rj", label: "React.js" },
  { value: "nx", label: "Next.js" },
  { value: "rd", label: "Full Stack" },
];

export const PROJECTS: Project[] = [
  {
    id: "movie-explorer",
    category: "rd",
    bgColor: "#1c1032",
    emoji: "🎬",
    featured: true,
    catLabel: "React Native + Node.js",
    catVariant: "muted",
    title: "Movie Explorer",
    description:
      "I built a full-stack movie discovery app powered by the TMDB API, with a typed API layer and TanStack Query driving infinite scroll, caching, and optimistic updates. The app includes in-app trailer playback, a Node.js/Express + SQLite + JWT backend deployed on Render, and a custom Android Kotlin native module. A Gemini-powered AI chat assistant with an animated FAB and rich markdown message rendering rounds out the experience, backed by global network-aware handling and FlatList performance tuning.",
    stack: [
      "React Native",
      "TypeScript",
      "TanStack Query",
      "TMDB API",
      "Node.js",
      "Express.js",
      "SQLite",
      "JWT",
      "Kotlin (Native Module)",
      "Google Gemini API",
      "Backend hosted on Render",
    ],
    links: false,
    demoUrl: "#",
    githubUrl: "https://github.com/akhilpasha12",
    demoLabel: "Live Demo →",
  },
  // {
  //   id: "cycle-tracker",

  //   category: "rn",

  //   bgColor: "#A51F4D",

  //   emoji: "🌸",

  //   featured: true,

  //   catLabel: "React Native + TypeScript",

  //   catVariant: "muted",

  //   title: "CycleTracker",

  //   description:
  //     "I built a privacy-focused menstrual cycle tracking app using React Native and TypeScript, with local SQLite storage for cycle history and daily logs. The app includes cycle predictions, period and ovulation estimates, calendar-based tracking, statistics, customizable reminders, and daily check-in notifications. Zustand manages application state, while Notifee handles scheduled notifications, notification actions, background events, and notification-driven navigation. The app is designed around an offline-first approach with a clean, focused mobile experience.",
  //   stack: [
  //     "React Native",
  //     "TypeScript",
  //     "Zustand",
  //     "SQLite",
  //     "Notifee",
  //     "React Navigation",
  //     "Android",
  //     "Local Storage",
  //   ],

  //   links: false,

  //   demoUrl: "#",

  //   githubUrl: "https://github.com/akhilpasha12",

  //   demoLabel: "Live Demo →",
  // },
  {
    id: "nep-portal",
    category: "rn",
    bgColor: "#1a1a2e",
    emoji: "📡",
    featured: true,
    catLabel: "React Native + React.js",
    catVariant: "orange",
    title: "National EMF Portal (NEP)",
    description:
      "I modernized Ramboll's EMF platform by migrating legacy systems to React and TypeScript and building a React Native app for telecom site audits. The app enables precise panoramic captures via Vision Camera integration, while offline support ensures data integrity in remote field locations. This end-to-end solution streamlines regulatory compliance and field workflows through high-performance mobile and web tools.",
    stack: [
      "React.js",
      "React Native",
      "TypeScript",
      "Tailwind CSS",
      "Vision Camera",
      "Formik",
      "Google Maps",
      "PanResponder",
    ],
    links: false,
    demoUrl: "#",
    githubUrl: "#",
    demoLabel: "Case Study",
  },
  {
    id: "inventory-qr",
    category: "rd",
    bgColor: "#0f2027",
    emoji: "📦",
    featured: true,
    catLabel: "R&D · Full Stack",
    catVariant: "dark",
    title: "Inventory & QR Management",
    description:
      "I engineered an end-to-end R&D product that automates warehouse workflows by integrating Bluetooth thermal printer SDKs for real-time QR label generation. The platform features a sophisticated scan-to-cart system and a Node.js/MongoDB backend, allowing for rapid inventory tracking and automated digital invoice generation.",
    stack: [
      "React Native",
      "Node.js",
      "MongoDB",
      "Express.js",
      "Thermal Printer SDK",
      "Camera Integration",
    ],
    links: false,
    demoUrl: "#",
    githubUrl: "#",
    demoLabel: "Case Study",
  },
  {
    id: "telecom-field",
    category: "rn",
    bgColor: "#FAE5CD",
    emoji: "🏗",
    catLabel: "React Native",
    catVariant: "orange",
    title: "Telecom Field Inspection",
    description:
      "I developed a specialized mobile application for telecom technicians to conduct site safety audits with a high-fidelity Before/After QC workflow. Built with a focus on reliability, the app utilizes AsyncStorage for robust offline-first capabilities, ensuring that critical evidence is captured and stored locally before being synced to the central portal.",
    stack: [
      "React Native",
      "AsyncStorage",
      "REST API",
      "Camera Integration",
      "Image Compression",
    ],
    links: false,
    demoUrl: "#",
    githubUrl: "#",
    demoLabel: "Case Study",
  },
  {
    id: "serrano-ecom",
    category: "rn",
    bgColor: "#2a1a00",
    emoji: "🛒",
    catLabel: "React Native + React.js",
    catVariant: "orange",
    title: "Serrano — E-Commerce",
    description:
      "I architected a scalable mobile e-commerce platform featuring adaptive UIs and complex global state management using Redux Toolkit. The app provides a seamless shopping experience with Razorpay payment gateway integration and real-time geolocation services.",
    stack: [
      "React Native",
      "Redux Toolkit",
      "Razorpay",
      "Firebase Auth",
      "MongoDB",
      "Geolocation APIs",
    ],
    links: false,
    demoUrl: "#",
    githubUrl: "#",
    demoLabel: "Live Demo →",
  },
  {
    id: "serrano-admin",
    category: "nx",
    bgColor: "#1a2f1a",
    emoji: "📊",
    catLabel: "Next.js",
    catVariant: "muted",
    title: "Admin Dashboard (Serrano)",
    description:
      "I built a real-time administrative nerve center using Next.js to manage complex e-commerce inventories and user permissions. The dashboard implements strict Role-Based Access Control (RBAC) and utilizes Formik for robust data validation, providing site administrators with a secure and efficient tool for daily operations.",
    stack: ["Next.js", "Tailwind CSS", "RBAC", "Context API"],
    links: false,
    demoUrl: "#",
    githubUrl: "#",
    demoLabel: "Live Demo →",
  },

  // {
  //   id: "syncfield-offline-sync",
  //   category: "rd",
  //   bgColor: "#0a1f1c",
  //   emoji: "🔄",
  //   catLabel: "React Native + Node.js",
  //   catVariant: "muted",
  //   title: "SyncField — Offline Data Sync App",
  //   description:
  //     "I designed and built an offline-first mobile application that reliably captures form data and images without internet connectivity and synchronizes them to a cloud backend when the network is restored. The system uses a local queue with idempotent API handling to prevent duplicate submissions and ensures seamless data consistency across unstable network conditions.",
  //   stack: [
  //     "React Native",
  //     "AsyncStorage",
  //     "NetInfo",
  //     "Node.js",
  //     "Express.js",
  //     "MongoDB Atlas",
  //     "Multer",
  //     "Axios",
  //     "Backend hosted on Render",
  //   ],
  //   links: false,
  //   demoUrl: "#",
  //   githubUrl: "#",
  //   demoLabel: "Live Demo →",
  // },
  {
    id: "connectlive-realtime-chat",
    category: "rd",
    bgColor: "#111827",
    emoji: "💬",
    catLabel: "React Native + Node.js",
    catVariant: "muted",
    title: "ConnectLive — Real-Time Chat App",
    description:
      "Built a real-time chat application with instant messaging, live location sharing, and push notifications using WebSockets. Implemented scalable backend APIs, persistent chat storage, and real-time communication for seamless user interaction.",
    stack: [
      "React Native",
      "Socket.IO",
      "Node.js",
      "Express.js",
      "MongoDB Atlas",
      "Firebase Cloud Messaging (FCM)",
      "React Native Maps",
      "Axios",
      "Backend hosted on Render",
    ],
    links: true,
    demoUrl: "/assets/video/demo.mp4",
    githubUrl: "https://github.com/akhilpasha12",
    demoLabel: "Live Demo →",
  },
  {
    id: "portfolio-dev",
    category: "rj",
    bgColor: "#0f172a",
    emoji: "🌐",
    catLabel: "React.js",
    catVariant: "orange",
    title: "v1 Personal Portfolio",
    description:
      "A high-performance personal showcase built with React and Tailwind CSS. It features a modular architecture using Custom Hooks for state logic and React Router for seamless client-side navigation. The UI focuses on a clean, utility-first aesthetic to highlight professional experience and project technicalities.",
    stack: ["React.js", "Tailwind CSS", "React Router", "Live on Netlify"],
    links: true,
    demoUrl: "https://akhilpasha.netlify.app/",
    githubUrl: "https://github.com/akhilpasha12",
    demoLabel: "View v1 Live →",
  },
];
