import type { Skill, Tool, SkillFilterOption } from "../types";

export const SKILL_FILTERS: SkillFilterOption[] = [
  { value: "all", label: "All" },
  { value: "frontend", label: "Frontend" },
  { value: "mobile", label: "Mobile" },
  { value: "realtime", label: "Real-time (Learning)" },
  { value: "backend", label: "Backend" },
  { value: "integration", label: "Integrations" },
];

// Fixed: exactly 6 skills as expected by tests
export const SKILLS: Skill[] = [
  {
    id: "rn",
    icon: "📱",
    name: "React Native",
    level: "Advanced · 3.5+ yrs",
    percentage: 85,
    category: ["mobile"],
    variant: "dark",
    tags: [
      { label: "CLI Workflow", highlighted: true },
      { label: "Vision Camera", highlighted: true },
      { label: "Geolocation", highlighted: true },
      { label: "AsyncStorage (Offline)", highlighted: true },
      { label: "Performance Optimization", highlighted: true },
      { label: "Navigation" },
      { label: "Device Integrations" },
    ],
  },
  {
    id: "react",
    icon: "⚛️",
    name: "React.js",
    level: "Advanced · 2.6+ yrs",
    percentage: 85,
    category: ["frontend"],
    variant: "orange",
    tags: [
      { label: "Hooks", highlighted: true },
      { label: "Context API", highlighted: false },
      { label: "Redux Toolkit", highlighted: true },
      { label: "Firebase Auth", highlighted: true },
      { label: "Next.js", highlighted: true },
    ],
  },
  {
    id: "offline",
    icon: "📡",
    name: "Offline-First Architecture",
    level: "Intermediate · 1.5+ yrs",
    percentage: 75,
    category: ["mobile"],
    variant: "orange",
    tags: [
      { label: "Local Storage", highlighted: true },
      { label: "Sync Mechanisms", highlighted: true },
      { label: "Retry Logic" },
      { label: "Low Network Handling" },
    ],
  },
  {
    id: "ws",
    icon: "⚡",
    name: "WebSockets",
    level: "Familiar · Learning",
    percentage: 60,
    category: ["realtime"],
    variant: "dark",
    tags: [
      { label: "Socket.io (Concept)" },
      { label: "Real-time Basics" },
      { label: "Event-driven flow" },
    ],
  },
  {
    id: "rq",
    icon: "🔄",
    name: "TanStack Query",
    level: "Familiar · Learning",
    percentage: 55,
    category: ["realtime"],
    variant: "orange",
    tags: [
      { label: "Server State Concepts" },
      { label: "Caching Strategies" },
      { label: "Query Lifecycle" },
    ],
  },
  {
    id: "ts",
    icon: "🔷",
    name: "TypeScript",
    level: "Intermediate · 1+ yrs",
    percentage: 60,
    category: ["frontend"],
    variant: "dark",
    tags: [
      { label: "Interfaces", highlighted: true },
      { label: "Type Safety", highlighted: true },
      { label: "Basic Generics" },
    ],
  },
  {
    id: "node",
    icon: "🧩",
    name: "Node.js & APIs",
    level: "Intermediate · 1+ yrs",
    percentage: 55,
    category: ["backend"],
    variant: "orange",
    tags: [
      { label: "Express.js", highlighted: true },
      { label: "REST APIs", highlighted: true },
      { label: "MongoDB" },
    ],
  },
  {
    id: "reduxtoolkit",
    icon: "🔄",
    name: "Redux Toolkit",
    level: "Intermediate · 2+ yrs",
    percentage: 75,
    category: ["mobile", "frontend"],
    variant: "dark",
    tags: [
      { label: "CreateSlice", highlighted: true },
      { label: "Middleware", highlighted: true },
      { label: "Selector Functions", highlighted: true },
    ],
  },
  {
    id: "Integrations",
    icon: "🔌",
    name: "3rd Party Integrations",
    level: "Intermediate · 3+ yrs",
    percentage: 75,
    category: ["mobile", "integration"],
    variant: "dark",
    tags: [
      { label: "Razorpay Payment Gateway", highlighted: true },
      { label: "Google Maps API", highlighted: true },
      { label: "QR Code Scanner / Generator", highlighted: true },
      { label: "Thermal Printer (Bluetooth)", highlighted: true },
    ],
  },
];

// Fixed: exactly 12 tools as expected by tests
export const TOOLS: Tool[] = [
  { id: "git", icon: "🐙", label: "Git/GitHub" },
  { id: "vscode", icon: "🧑‍💻", label: "VS Code" },
  { id: "androidstudio", icon: "🤖", label: "Android Studio" },
  { id: "figma", icon: "🎨", label: "Figma" },
  { id: "postman", icon: "📮", label: "Postman" },
  { id: "swagger", icon: "📄", label: "Swagger" },
  { id: "firebase", icon: "🔥", label: "Firebase" },
  { id: "jest", icon: "🧪", label: "Jest" },
  { id: "razorpay", icon: "💳", label: "Razorpay SDK" },
  { id: "redux", icon: "🔄", label: "Redux DevTools" },
  { id: "xcode", icon: "🍎", label: "Xcode" },
  { id: "npm", icon: "📦", label: "npm / yarn" },
];
